apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-app-spring
  labels:
    app: rest-app-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app-spring
  template:
    metadata:
      labels:
        app: rest-app-spring
    spec:
      containers:
        - name: rest-app-spring
          image: rest-service/jar:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pass
                  key: postgres-user-password
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres-server
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name:  postgres-configmap
                  key: postgres-database-name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres-user-username
---
apiVersion: v1
kind: Service
metadata:
  name: rest-app-spring
  labels:
    app: rest-app-spring
spec:
  type: NodePort
  selector:
    app: rest-app-spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
