apiVersion: v1
kind: Service
metadata:
  name: rest-app-postgres
  labels:
    app: rest-app
spec:
  ports:
    - port: 5432
  selector:
    app: rest-app
    tier: postgres
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: rest-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-app-postgres
  labels:
    app: rest-app
spec:
  selector:
    matchLabels:
      app: rest-app
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rest-app
        tier: postgres
    spec:
      containers:
        - image: postgres:16.2-alpine3.19
          name: postgres
          env:
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres-database-name
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres-user-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pass
                  key: postgres-user-password
          livenessProbe:
            tcpSocket:
              port: 5432
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgres
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
